env:
  es2021: true
  node: true
extends:
  - noir/all
parserOptions:
  project: ./tsconfig.eslint.json
  ecmaVersion: latest
  sourceType: module
rules:
  multiline-comment-style: off
  import/no-relative-parent-imports: off
  import/extensions: off
